/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kodlar;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Feyyaz
 */
public class Normal_Carpim_Jframe extends javax.swing.JFrame {

    /**
     * Creates new form Normal_Carpim_Jframe
     */
    int satir_sayisi;
    int[][] matris1;
    int[][] matris2;
    int[][] sonuc_matris;
    float toplam = 0;
    float ort = 0;

    public Normal_Carpim_Jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("matris boyutu giriniz :");

        jButton1.setText("çarp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("süre : ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        long nanoTime_bas = System.nanoTime();

        satir_sayisi = Integer.parseInt(jTextField1.getText());

        System.out.println("burası2");
        matris1 = new int[satir_sayisi][satir_sayisi];
        matris2 = new int[satir_sayisi][satir_sayisi];
        sonuc_matris = new int[satir_sayisi][satir_sayisi];

        int sayi;
        int topla = 0;

        Random rasgele = new Random();
        System.out.println("burası");

        for (int i = 0; i < satir_sayisi; i++) {
            for (int j = 0; j < satir_sayisi; j++) {
                sayi = 1 + rasgele.nextInt(100);
                matris1[i][j] = sayi;
                sayi = 1 + rasgele.nextInt(100);
                matris2[i][j] = sayi;
            }
        }

        System.out.println("-----------");
        
        for (int i = 0; i < satir_sayisi; i++) {
            for (int j = 0; j < satir_sayisi; j++) {
                for (int k = 0; k < satir_sayisi; k++) {
                    topla = topla + matris1[i][k] * matris2[k][j];
                }
                sonuc_matris[i][j] = topla;
                topla = 0;
            }
        }

        File dosya1 = null;
        FileWriter yazici1 = null;
        BufferedWriter yaz1 = null;
        File dosya2 = null;
        FileWriter yazici2 = null;
        BufferedWriter yaz2 = null;
        File dosya3 = null;
        FileWriter yazici3 = null;
        BufferedWriter yaz3 = null;

        dosya1 = new File("D://txt_dosyaları//matris1_" + satir_sayisi + ".txt");

        if (!dosya1.exists()) {
            try {
                dosya1.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dosya2 = new File("D://txt_dosyaları//matris2_" + satir_sayisi + ".txt");
        if (!dosya2.exists()) {
            try {
                dosya2.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dosya3 = new File("D://txt_dosyaları//matris_sonuc_" + satir_sayisi + ".txt");
        if (!dosya3.exists()) {
            try {
                dosya3.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            yazici1 = new FileWriter(dosya1, false);
            yaz1 = new BufferedWriter(yazici1);
            yazici2 = new FileWriter(dosya2, false);
            yaz2 = new BufferedWriter(yazici2);
            yazici3 = new FileWriter(dosya3, false);
            yaz3 = new BufferedWriter(yazici3);
        } catch (IOException ex) {
            Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            for (int i = 0; i < satir_sayisi; i++) {
                for (int j = 0; j < satir_sayisi; j++) {
                    yaz1.write(matris1[i][j] + "\t");
                    yaz2.write(matris2[i][j] + "\t");
                    yaz3.write(sonuc_matris[i][j] + "\t");
                }

                yaz1.write("\n");
                yaz2.write("\n");
                yaz3.write("\n");
            }

            yaz1.close();
            yaz2.close();
            yaz3.close();
        } catch (IOException ex) {
            Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(Level.SEVERE, null, ex);
        }

        long nanoTime_bit = System.nanoTime();
        long fark = nanoTime_bit - nanoTime_bas;

        jTextArea1.setText("geçen süre(sn) : " + (float) (fark / (float) 1000000000));

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Normal_Carpim_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Normal_Carpim_Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
